services:
  blip:
    build:
      context: .
      args:
        REACT_APP_URL: ${REACT_APP_URL}
        REACT_APP_KEY: ${REACT_APP_KEY}
    env_file: .env
    ports:
      - "8001:3000"
    container_name: blip
    restart: unless-stopped
